### ISSUE TITLE
Profile buyer show

### ISSUE THREAD

**Issue by IIIIIHIIIII** [17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod/dropzone_ruby#1]
dropzone profile buyer show 1LXFn2qmDr2ShcvYZQDcmjfPA7pFhGT9Es

shows 

error: Counterparty::TxDecode::UndefinedBehavior.

**Comment by 17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod** [comment]
This would appear to be fixed. It seems as if a buyer profile was created, without any attributes attached. I will release an updated version of the gem with a few additional features, and this fix. In the meantime, you may want to download and run the program directly from this repo.
