### ISSUE TITLE
White paper on github ?

### ISSUE THREAD

**Issue by ianpurton** [17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod/dropzone_ruby#10]
I was a bit wary of downloading the whitepaper from metzdowd link. Looks a bit dodgy. Can you host the whitepaper as part of this repository ?

**Comment by krisives** [comment]
It's in the repository:

https://github.com/17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod/dropzone_ruby/blob/master/Drop%20Zone%20-%20An%20Anonymous%20Peer-To-Peer%20Local%20Contraband%20Marketplace.pdf

**Comment by krisives** [comment]
I don't mind the name of the paper (in terms of content) but you may want to simply call it "Whitepaper.pdf" or "Dropzone.pdf" similar to how Satoshi originally did it.

**Comment by 17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod** [comment]
That's easy enough. How did Satoshi do it, did he label the document,  "Whitepaper.pdf" or "Bitcoin.pdf"?

**Comment by krisives** [comment]
I think it's always been called "bitcoin.pdf" now that I look closer. I know it's always been available as "bitcoin.pdf" at:

https://bitcoin.org/bitcoin.pdf

From what I know the first time it was published was in 2008 here:

https://www.mail-archive.com/cryptography@metzdowd.com/msg09959.html

**Comment by 17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod** [comment]
Renamed.
