### ISSUE TITLE
Initiating a chat with yourself disables displaying messages from other conversations

### ISSUE THREAD

**Issue by ghost** [17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod/dropzone_ruby#11]
To reproduce just start a chat with yourself doing:

```
dropzone chat new <my_testnet_wif_priv_key> <my_corresponding_testnet_addr>
```

Once included in a block, the application should fail displaying messages from other conversations. I've coded [a little workaround](https://gist.github.com/aynik/ab5d680f473d0421992e) for ignoring chats with myself.

**Comment by ScroogeMcDuckButWithBitcoin** [comment]
Added a quick check to the new session which prevents conversations from addressing to oneself in the first place. Maybe there's a better way to fix this in the future, but this works for now.
