### ISSUE TITLE
I don't know how to message you via PGP key

### ISSUE THREAD

**Issue by droplister** [17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod/dropzone_ruby#12]
I'm not aware of how to contact someone with their PGP key alone. I can certainly encrypt the message, but other than that... I don't know what to do with it.

And since my comments aren't of a very sensitive nature, I posted them here: http://pastebin.com/saWEU8LZ

**Comment by 17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod** [comment]
My testnet address is mw8Ge8HDBStKyn8u4LTkUwueheFNhuo7Ch . Though, I am not a person who is generally fond of communicating.
