### ISSUE TITLE
Simple Flag for Outputs

### ISSUE THREAD

**Issue by droplister** [17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod/dropzone_ruby#15]
I noticed while indexing items on the block-chain that I had to clean up the output of the commands due to the markup.

It would be nice if there were a flag, like --simple that removed decoration:

```
-------------------
|  data: value    |
-------------------
```

To:

```
data: value
```

Or JSON would be awesome. A --json flag perhaps?

```
{
    "data": "value"
}
```

Particularly, I would like it for: dropzone listing find. The only thing I really need from that command is the txid of the listing because I can do a follow up: dropzone listing show.

My use case is that I don't know ruby, so I am using PHP to run Ruby commands and cleaning up the output with regex. I imagine other people could benefit from such a change though.

If you're using the command line as a user, it's all good. If you're running the commands inside a script, it's less great.

**Comment by ScroogeMcDuckButWithBitcoin** [comment]
I like this suggestion. It's not the highest priority for me atm, but I will have time for this after the js lib is up to par. I intend to make a couple other minor changes to this cli at that time.

**Comment by ScroogeMcDuckButWithBitcoin** [comment]
Added a --output_json flag, which does what you want (I think!)

**Comment by droplister** [comment]
:+1:
