### ISSUE TITLE
Allows for creation of orders that have a radius bigger than is allowed

### ISSUE THREAD

**Issue by junseth** [17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod/dropzone_ruby#17]
The code supports radiuses of 6 characters, meaning the largest radius is 999999. I put in an 8 character radius, and it listed as the following:
+----------------------------------------------------------------------------------+
| Listing: 13qwP1UsYxB66vF4QTJLbu1112AQkR7V1P                                      |
+----------------------------------------------------------------------------------+
| latitude      : 39.8282                                                          |
| longitude     : -98.5795                                                         |
| radius        : 2011680                                                          |
| price_currency: USD                                                              |
| price_in_units: 30                                                               |
| description   : #black #baseball-cap #Drop-Zone written on the front. Signed by  |
|               : #brighton36 and #junseth http://bit.ly/1k5lV6I                   |
+----------------------------------------------------------------------------------+
| Tx: 73cfb35e1e6bb31b3ddffb41322c46f155970bfae3c40385b171ba02f88985a0             |
+----------------------------------------------------------------------------------+

**Comment by ScroogeMcDuckButWithBitcoin** [comment]
This would appear to be the command: 

```
dropzone listing create --latitude "39.8282" --longitude "-98.5795" --radius 999999 --price_currency 'USD' --price_in_units 30 --description "#black #baseball-cap #Drop-Zone written on the front. Signed by #brighton36 and #junseth http://bit.ly/1k5lV6I" <private key>
```

**Comment by ScroogeMcDuckButWithBitcoin** [comment]
@junseth The supplied command is valid, and would not produce an erroneous item as the radius is less than the max (by one).

Here's the max:

```
 validates_if_present :radius, less_than: 1000000, if: 'create_txid.nil?
```

**Comment by ScroogeMcDuckButWithBitcoin** [comment]
However, this fails: 

```
dropzone --force_testnet listing create --latitude "39.8282" --longitude "-98.5795" --radius 9999999 --price_currency 'USD' --price_in_units 30 --description "#black #baseball-cap #Drop-Zone written on the front. Signed by #brighton36 and #junseth http://bit.ly/1k5lV6I" <private key>
```

**Comment by ScroogeMcDuckButWithBitcoin** [comment]
Fixed. Seems like validation wasn't being performed before persistence. Command now outputs:

```
Errors Found in Listing:
 * "radius": must be less than 1000000
```

https://github.com/ScroogeMcDuckButWithBitcoin/dropzone_ruby/commit/9f9f1126813f9ecc51aa35122f55fb3d92953e48
