### ISSUE TITLE
Can't pull profile listing of seller

### ISSUE THREAD

**Issue by junseth** [17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod/dropzone_ruby#18]
I created a product with too big of a radius before I created a seller profile. When I created the seller profile, everything seemed fine, but when I go to pull the seller profile, it gives me the following error.

error: undefined method `length' for nil:NilClass. Use --trace to view backtrace

This is the command to replicate the error:
dropzone profile seller show 14zBTbnhzHjdAKkaR4J9kCPiyVyNoaqoti

**Comment by ScroogeMcDuckButWithBitcoin** [comment]
Fixed https://github.com/ScroogeMcDuckButWithBitcoin/dropzone_ruby/blob/1644ca9c18a0797ec68328976b04a9842a0abda3/spec/item_spec.rb#L293-L331
