### ISSUE TITLE
Testnet only transactions (chat message) should have a higher tip default

### ISSUE THREAD

**Issue by stoicism2323** [17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod/dropzone_ruby#31]
It seems to me like 20000 is too low of a default tip for testnet-only operations that should be optimised for speed. Not sure what a better default is but maybe 50000 is a start. Is there a reason to keep it at 20000? Thanks

**Comment by ScroogeMcDuckButWithBitcoin** [comment]
Not particularly - are the transactions not getting confirmed at 20,000? I didn't think testnet miners were too picky...

**Comment by ScroogeMcDuckButWithBitcoin** [comment]
I think this is not worth changing for now, unless you're having a hard time with confirmations. Re-open this please if you are.
