### ISSUE TITLE
SoChain response error when running 'chat say'

### ISSUE THREAD

**Issue by stoicism2323** [17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod/dropzone_ruby#33]
When trying to run a chat say command, I get the following response:

error: SoChain::ResponseError. Use --trace to view backtrace

with --debug, I get

RestClient.get "https://chain.so/api/v2/tx/BTCTEST/n4Gy5tDQthje9YTYWC88TbwuKdXHo18BGg", "Accept"=>"application/json", "Accept-Encoding"=>"gzip, deflate", "Content-Type"=>"application/json"
14:31:00 Connecting directly to chain.so:443
14:31:00 Connected to chain.so:443
# => 500 InternalServerError | application/json 95 bytes

error: SoChain::ResponseError. Use --trace to view backtrace

with --trace, I get

/home/lhost/github/dropzone/dropzone-ruby/lib/so_chain.rb:99:in `rescue in block in json_get': SoChain::ResponseError (SoChain::ResponseError)
    from /home/lhost/github/dropzone/dropzone-ruby/lib/so_chain.rb:90:in`block in json_get'
    from /home/lhost/github/dropzone/dropzone-ruby/lib/so_chain.rb:80:in `request'
    from /home/lhost/github/dropzone/dropzone-ruby/lib/so_chain.rb:88:in`json_get'
    from /home/lhost/github/dropzone/dropzone-ruby/lib/so_chain.rb:23:in `getrawtransaction'
    from /home/lhost/github/dropzone/dropzone-ruby/lib/dropzone/connection.rb:136:in`tx_by_id'
    from /home/lhost/github/dropzone/dropzone-ruby/lib/dropzone/message_base.rb:191:in `find'
    from /home/lhost/github/dropzone/dropzone-ruby/lib/dropzone/command.rb:290:in`chat_say'
    from /home/lhost/.gem/ruby/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:179:in `call'
    from /home/lhost/.gem/ruby/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in`run'
    from /home/lhost/.gem/ruby/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
    from /home/lhost/.gem/ruby/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:68:in`run!'
    from /home/lhost/.gem/ruby/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
    from /home/lhost/.gem/ruby/2.3.0/gems/commander-4.4.0/lib/commander/import.rb:5:in`block in <top (required)>'

Thanks

**Comment by ScroogeMcDuckButWithBitcoin** [comment]
If you look at the url: https://chain.so/api/v2/tx/BTCTEST/n4Gy5tDQthje9YTYWC88TbwuKdXHo18BGg It doesnt process on their end. And, that address doesn't look valid. In fact, it looks like a private key maybe? :/

**Comment by stoicism2323** [comment]
Yup, I was being an idiot here. Brings me to my next point: is there any way to have DZ check if I fucked up bad like this and put a private key where the chat session id is supposed to be? Otherwise no issue here... thanks

**Comment by stoicism2323** [comment]
I have added the following line to my version of lib/dropzone.command.rb in order to make sure I don't accidentally put in a base58 address, in the functions chat say and chat show (command.rb:255 and command.rb:333)

raise OptionParser::InvalidArgument, 'txid' if Bitcoin.decode_base58 txid

However, this does not prevent the case where a user accidentally puts in their private key as a hex value. Makes sense to me if you don't wanna add this to dropzone however as it is definitely not necessary to check for. Thanks

**Comment by ScroogeMcDuckButWithBitcoin** [comment]
This was a good idea, but I didn't like the decode_base58 implementation. Instead I went with /\A[a-f0-9]{64}\Z/i.match(txid)

**Comment by ScroogeMcDuckButWithBitcoin** [comment]
(Pushed btw )
