### ISSUE TITLE
bundle install

### ISSUE THREAD

**Issue by Jeremy-coding** [17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod/dropzone_ruby#5]
Tried installing the bundle in order to run the test suite.  Got

---

dropzone_ruby $bundle install
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Using rake 10.4.2
Using bitcoin-ruby 0.0.7
Installing highline 1.7.2
Installing commander 4.3.4
Installing ffi 1.9.10
Using unf_ext 0.0.7.1
Using unf 0.1.4
Using domain_name 0.5.24
Using http-cookie 1.0.2
Using mime-types 2.6.1
Using netrc 0.10.3
Using rest-client 1.8.0
Using ruby-rc4 0.1.5
Using counterparty_ruby 1.2.0
Using diff-lcs 1.2.5
Installing sequel 4.21.0
Using socksify 1.7.0
Using sqlite3 1.3.10
Using veto 1.0.1

dropzone_ruby at /Users/XXXXXXXXXXXX/Code/dropzone_ruby did not have a valid gemspec.
This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
The validation message from Rubygems was:
  ["-", "An", "Anonymous", "Contraband", "Drop", "Local", "Marketplace.pdf", "Peer-To-Peer", "Zone"] are not files
Using dropzone_ruby 0.1 from source at .
Using rdoc 4.2.0
Installing rspec-support 3.2.2
Installing rspec-core 3.2.3
Installing rspec-expectations 3.2.1
Installing rspec-mocks 3.2.1
Installing rspec 3.2.0
Installing sham 1.1.0
Using bundler 1.6.1
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.

---

Rspec stacked full of errors when run, but I assume this was probably because of the gem install failures.

**Comment by 17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod** [comment]
It _looks_ to me as if you're running the github version of this library, instead of the gem version. That was a bug that I found during packaging, and had yet to push. I have resolved that on my end, and shall push that change shortly. Until then, change line 10 of dropzone_ruby.gemspec to

```
  gem.files         = `git ls-files`.split(/\n/m)

```
