### ISSUE TITLE
Conversation flow

### ISSUE THREAD

**Issue by ghost** [17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod/dropzone_ruby#8]
I noticed that conversations are flowing upwards instead of downwards. I think is more difficult to read this way. Any reason it is like this?

**Comment by krisives** [comment]
They are currently in reverse chronological order? Is it currently newer comments first instead of like here on GitHub where older comments are listed first?

**Comment by ghost** [comment]
Yep, exactly, they're like that. I haven't checked thoroughly but now it occurred to me that this could happen if blockr.io is returning the transactions ordered by descending block height or timestamp.

**Comment by krisives** [comment]
Yikes! I was not aware this project was using the blockr.io API instead of looking to the blockchain. That's no good =(

**Comment by ghost** [comment]
Yep, not what everybody prefers but the original author was honest with that, he implemented it as a module which can be eventually switched for SPV. I'm [reimplementing this client for node.js](https://github.com/17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod/dropzone_js) and I plan to add SPV there, keep on touch for updates.

**Comment by krisives** [comment]
Does your JS re-implementation do the under-the-hood bits or a GUI as well? Let me know if you want work on a node-webkit GUI.

**Comment by ghost** [comment]
That would be amazing, this tool would benefit greatly having a graphical interface. I will build the client as a library too, not only as a command line tool, so the functionality will be fully exposed.

**Comment by krisives** [comment]
I'll start a node-webkit GUI later today and work with the binary using child_process until your nodejs implementation is finished. My goal is just a simple Bootstrap UI to start with.

**Comment by ghost** [comment]
Wonderful! I you want to test a bit the platform, feel free to send me messages using it to mmtztEC4ZZtc78RgmGkx23vRYDe36TZWCW. You would need to create a session first using `dropzone communication new <testnet_private_key_wif> mmtztEC4ZZtc78RgmGkx23vRYDe36TZWCW`

**Comment by 17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod** [comment]
@krisives - Please send me a message as well. 

Regarding this Issue, I intend to rework the cli interface here shortly. I will incorporate the origin reversal in those changes. Most of the meaningful work going forward on this project will likely revolve around the GUI. It was my intent with this CLI version to get something up quickly, and provide a server-side implementation before the client side. Let's move this discussion into the (newly renamed) node-dropzone repo?
